"""
Deterministic recovery candidate templates — FEAT-016.

Generates correction candidates from established knowledge without LLM.
Priority order (TAD §8, BACKEND_SPEC §6):
1. ESTABLISHED recovery memory
2. VALIDATED recovery memory
3. Provider-configured safe mappings
4. Schema-compatible transformations
5. Safe transient retry behavior

Each candidate includes action type, changes, evidence IDs, confidence, source.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from typing import Any

from app.context.builder import FailureContext
from app.failures.classifier import FailureClass
from app.models.recovery import (
    MATURITY_ESTABLISHED,
    MATURITY_VALIDATED,
    PROVENANCE_DETERMINISTIC,
)


@dataclass
class DeterministicCandidate:
    """
    A correction candidate generated by the deterministic engine.

    Must carry evidence (TAD §8).
    Provenance is always DETERMINISTIC for candidates from this module.
    """
    action_type: str
    changes: list[dict[str, Any]]
    reason: str
    confidence: float
    evidence_ids: list[str] = field(default_factory=list)
    source: str = PROVENANCE_DETERMINISTIC
    recovery_case_id: uuid.UUID | None = None
    maturity_source: str | None = None


def generate_retry_candidate(context: FailureContext) -> DeterministicCandidate | None:
    """
    Generate a safe transient retry candidate.

    Only for RATE_LIMIT (with retry-after) and CONNECTION_FAILURE.
    This is a priority-5 (lowest) deterministic candidate.
    """
    if context.failure_class == FailureClass.RATE_LIMIT:
        retry_after = context.error_summary.get("retry_after")
        return DeterministicCandidate(
            action_type="retry_after",
            changes=[{"action": "wait_and_retry", "retry_after_seconds": retry_after or 1}],
            reason="Rate limit exceeded; retry after specified interval",
            confidence=0.80,
            evidence_ids=["failure_class:RATE_LIMIT"],
            maturity_source="TRANSIENT_RETRY",
        )
    if context.failure_class == FailureClass.CONNECTION_FAILURE:
        return DeterministicCandidate(
            action_type="retry_after",
            changes=[{"action": "wait_and_retry", "retry_after_seconds": 2}],
            reason="Transient connection failure; retry with backoff",
            confidence=0.60,
            evidence_ids=["failure_class:CONNECTION_FAILURE"],
            maturity_source="TRANSIENT_RETRY",
        )
    if context.failure_class == FailureClass.UPSTREAM_5XX:
        return DeterministicCandidate(
            action_type="retry_after",
            changes=[{"action": "wait_and_retry", "retry_after_seconds": 1}],
            reason="Upstream 5xx error; retry once",
            confidence=0.55,
            evidence_ids=["failure_class:UPSTREAM_5XX"],
            maturity_source="TRANSIENT_RETRY",
        )
    return None


def generate_from_recovery_case(
    context: FailureContext,
    case: Any,  # RecoveryCase ORM model
) -> DeterministicCandidate:
    """
    Generate a candidate from a stored recovery case.

    Priority 1 (ESTABLISHED) or 2 (VALIDATED).
    """
    # Base confidence from maturity and case confidence
    maturity_boost = {
        MATURITY_ESTABLISHED: 0.15,
        MATURITY_VALIDATED: 0.05,
    }
    base_confidence = min(
        case.confidence + maturity_boost.get(case.maturity, 0.0),
        1.0,
    )

    correction = case.correction or {}

    return DeterministicCandidate(
        action_type=correction.get("type", "unknown"),
        changes=correction.get("changes", []),
        reason=f"Historical recovery case ({case.maturity}); reuse count={case.reuse_count}",
        confidence=base_confidence,
        evidence_ids=[str(case.id)],
        recovery_case_id=case.id,
        maturity_source=case.maturity,
    )
